language: generic
sudo: required
services:
    - docker

before-install:
    - docker build -t levomeno/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true levomeno/docker-react npm run test